# Generated by Django 3.2.5 on 2021-07-13 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('failed', 'Failed'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('hitmen_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_hits', to=settings.AUTH_USER_MODEL)),
                ('managed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_hits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
